"use client";
import Link from "next/link";
import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { sdk } from "@/lib/sdk";
import { useGoals, useFeasibility, type Goal } from "./planning-queries";
import { unwrap } from "./queries";
import { action, secondary, control, Field, Panel, PageTitle, ErrorNotice, Loading, Empty, money, date } from "./ui";

export function GoalForm({ goal, onSaved }: { goal?: Goal; onSaved: () => void }) {
  const client = useQueryClient(); const [error, setError] = useState<unknown>(); const [pending, setPending] = useState(false);
  async function submit(form: FormData) {
    setPending(true); setError(null);
    const get = (key: string) => String(form.get(key) ?? "");
    const body = { name: get("name"), category: get("category") as Goal["category"], targetAmount: get("targetAmount"), targetDate: get("targetDate"), currentSavings: get("currentSavings"), monthlyContribution: get("monthlyContribution") };
    try {
      if (goal) unwrap(await sdk.PATCH("/api/v1/goals/{id}", { params: { path: { id: goal.id } }, body: { ...body, expectedRevision: goal.revision } }));
      else unwrap(await sdk.POST("/api/v1/goals", { body }));
      await Promise.all([client.invalidateQueries({ queryKey: ["goals"] }), client.invalidateQueries({ queryKey: ["planning"] })]); onSaved();
    } catch (e) { setError(e); } finally { setPending(false); }
  }
  return <form action={submit} className="space-y-4"><Field label="Goal name" name="name" required maxLength={100} defaultValue={goal?.name} /><label className="block">Goal category<select className={control} name="category" defaultValue={goal?.category ?? "savings"}>{["home", "car", "travel", "savings", "education", "medical", "retirement", "custom"].map(c => <option key={c}>{c}</option>)}</select></label><Field label="Target amount today (INR)" name="targetAmount" required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" defaultValue={goal?.targetAmount} /><Field label="Target date" name="targetDate" type="date" required defaultValue={goal?.targetDate} /><Field label="Already saved (INR)" name="currentSavings" required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" defaultValue={goal?.currentSavings} hint="Enter 0 only if you have not saved anything for this goal." /><Field label="Your monthly contribution (INR)" name="monthlyContribution" required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" defaultValue={goal?.monthlyContribution} hint="You choose the amount. We will explain whether it fits your plan." /><ErrorNotice error={error} /><button className={action} disabled={pending}>{pending ? "Saving…" : "Save goal"}</button></form>;
}
export function Goals({ onboarding = false }: { onboarding?: boolean }) {
  const query = useGoals(); const feasibility = useFeasibility(); const [adding, setAdding] = useState(false);
  return <>{!onboarding && <PageTitle title="Goals" description="Make room for what matters. Choose contributions for up to three active goals." />}<ErrorNotice error={query.error} retry={() => void query.refetch()} />{query.isPending && <Loading />}{feasibility.data?.overAllocated && <div role="status" className="mb-5 rounded-xl border border-[#8A531D] p-4 text-[#8A531D]">Your contributions exceed available monthly capacity. Review your goal contributions or monthly money. Your chosen amounts have been kept.</div>}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{query.data?.map(goal => <Panel key={goal.id} title={goal.name}><dl className="space-y-3"><div><dt className="text-sm text-muted-foreground">Target today</dt><dd className="text-2xl tabular-nums">{money(goal.targetAmount)}</dd></div><div><dt className="text-sm text-muted-foreground">By</dt><dd>{date(goal.targetDate)}</dd></div><div><dt className="text-sm text-muted-foreground">Your monthly contribution</dt><dd className="tabular-nums">{money(goal.monthlyContribution)}</dd></div></dl><Link className={`${secondary} mt-5`} href={`/dashboard/goals/${goal.id}`}>Review goal</Link></Panel>)}</div>{query.data?.length === 0 && <Empty>Start with a goal you care about. You can also continue and add goals later.</Empty>}{query.data && query.data.length < 3 && <div className="mt-5">{adding ? <Panel title="Add a goal"><GoalForm onSaved={() => setAdding(false)} /><button className={`${secondary} mt-3`} onClick={() => setAdding(false)}>Cancel</button></Panel> : <button className={secondary} onClick={() => setAdding(true)}>Add a goal</button>}</div>}{query.data?.length === 3 && <p className="mt-5 text-muted-foreground">You have three active goals. Remove one before adding another.</p>}</>;
}
export function GoalDetail({ id }: { id: string }) {
  const query = useGoals(); const feasibility = useFeasibility(); const client = useQueryClient(); const [editing, setEditing] = useState(false); const [confirm, setConfirm] = useState(false); const [error, setError] = useState<unknown>(); const [pending, setPending] = useState(false);
  const goal = query.data?.find(g => g.id === id);
  async function remove() { setPending(true); try { unwrap(await sdk.DELETE("/api/v1/goals/{id}", { params: { path: { id } } })); await Promise.all([client.invalidateQueries({ queryKey: ["goals"] }), client.invalidateQueries({ queryKey: ["planning"] })]); } catch (e) { setError(e); } finally { setPending(false); } }
  if (query.isPending) return <Loading />;
  if (!goal) return <><ErrorNotice error={query.error} retry={() => void query.refetch()} /><Empty href="/dashboard/goals" label="View goals">This goal is no longer active or could not be found.</Empty></>;
  const result = feasibility.data?.goals.find(g => g.id === id);
  return <><PageTitle title={goal.name} description={`Target ${money(goal.targetAmount)} by ${date(goal.targetDate)}`}><Link href="/dashboard/plan" className={action}>Update Plan</Link></PageTitle><div className="grid gap-6 lg:grid-cols-[1.85fr_1fr]"><div className="space-y-6"><Panel title="Your progress"><dl className="grid gap-5 sm:grid-cols-2"><div><dt>Already saved</dt><dd className="mt-2 text-3xl tabular-nums">{money(goal.currentSavings)}</dd></div><div><dt>Monthly contribution</dt><dd className="mt-2 text-3xl tabular-nums">{money(goal.monthlyContribution)}</dd></div></dl><p className="mt-6 text-muted-foreground">Your target is in today’s money. The plan accounts for inflation and return assumptions when evaluating funding.</p></Panel><Panel title="Funding outlook"><ErrorNotice error={feasibility.error} retry={() => void feasibility.refetch()} />{feasibility.isPending && <Loading />}{result && <><p className="text-2xl tabular-nums">{money(result.result.requiredSip)} per month required</p><p className="mt-3 text-muted-foreground">Calculated by the planning engine. Review the assumptions in your saved plan before changing your contribution.</p></>}</Panel></div><div className="space-y-6"><Panel title={editing ? "Edit goal" : "Your contribution"}>{editing ? <GoalForm goal={goal} onSaved={() => setEditing(false)} /> : <><p className="text-3xl tabular-nums">{money(goal.monthlyContribution)}</p><p className="my-4 text-muted-foreground">Changes are saved to your inputs. Update your plan when you are ready.</p><button className={secondary} onClick={() => setEditing(true)}>Edit Goal</button></>}</Panel><Panel title="Manage goal"><ErrorNotice error={error} />{confirm ? <div className="space-y-3"><p>Remove this active goal? Existing saved plan versions keep their previous assumptions.</p><button className={secondary} disabled={pending} onClick={() => void remove()}>{pending ? "Removing…" : "Confirm removal"}</button><button className={secondary} onClick={() => setConfirm(false)}>Keep goal</button></div> : <button className={secondary} onClick={() => setConfirm(true)}>Remove goal</button>}</Panel></div></div></>;
}
