/**
 * Typed Asset Registry for Financial Dream Planner
 * All 241 existing PNG assets cataloged with exact paths, intrinsic dimensions,
 * semantic purpose, and accessibility classification (decorative vs content).
 * Preserves all original raster assets from public/Assets.
 */

export type AssetPurpose =
  | "hero-character"
  | "character-illustration"
  | "financial-chart"
  | "financial-metric-preview"
  | "ui-widget"
  | "housing-goal"
  | "savings-goal"
  | "brand-accent"
  | "icon"
  | "status-indicator"
  | "palette-swatch"
  | "product-artifact";

export interface AssetMetadata {
  path: string;
  width: number;
  height: number;
  aspectRatio: number;
  folder: string;
  purpose: AssetPurpose;
  isDecorative: boolean;
  alt: string;
}

export const ASSET_REGISTRY: Record<string, AssetMetadata> = {
  "/Assets/Assets/add_transaction_form.png": {
    path: "/Assets/Assets/add_transaction_form.png",
    width: 451,
    height: 295,
    aspectRatio: 1.5288,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Add transaction form",
  },
  "/Assets/Assets/all_filter_chip.png": {
    path: "/Assets/Assets/all_filter_chip.png",
    width: 70,
    height: 44,
    aspectRatio: 1.5909,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "All filter chip",
  },
  "/Assets/Assets/amazon_transaction_row.png": {
    path: "/Assets/Assets/amazon_transaction_row.png",
    width: 286,
    height: 67,
    aspectRatio: 4.2687,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Amazon transaction row",
  },
  "/Assets/Assets/asset_006.png": {
    path: "/Assets/Assets/asset_006.png",
    width: 137,
    height: 28,
    aspectRatio: 4.8929,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Assets illustration",
  },
  "/Assets/Assets/asset_011.png": {
    path: "/Assets/Assets/asset_011.png",
    width: 69,
    height: 20,
    aspectRatio: 3.45,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Assets illustration",
  },
  "/Assets/Assets/asset_012.png": {
    path: "/Assets/Assets/asset_012.png",
    width: 184,
    height: 52,
    aspectRatio: 3.5385,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Assets illustration",
  },
  "/Assets/Assets/asset_allocation_bars.png": {
    path: "/Assets/Assets/asset_allocation_bars.png",
    width: 329,
    height: 165,
    aspectRatio: 1.9939,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Asset allocation bars",
  },
  "/Assets/Assets/boarding_pass_flight.png": {
    path: "/Assets/Assets/boarding_pass_flight.png",
    width: 491,
    height: 252,
    aspectRatio: 1.9484,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Boarding pass flight",
  },
  "/Assets/Assets/cash_bundle_download.png": {
    path: "/Assets/Assets/cash_bundle_download.png",
    width: 262,
    height: 200,
    aspectRatio: 1.31,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cash bundle download",
  },
  "/Assets/Assets/category_filter_chip.png": {
    path: "/Assets/Assets/category_filter_chip.png",
    width: 105,
    height: 41,
    aspectRatio: 2.561,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Category filter chip",
  },
  "/Assets/Assets/compounding_in_action.png": {
    path: "/Assets/Assets/compounding_in_action.png",
    width: 766,
    height: 160,
    aspectRatio: 4.7875,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Compounding in action",
  },
  "/Assets/Assets/emi_due_calendar.png": {
    path: "/Assets/Assets/emi_due_calendar.png",
    width: 338,
    height: 412,
    aspectRatio: 0.8204,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Emi due calendar",
  },
  "/Assets/Assets/europe_calling_postcard.png": {
    path: "/Assets/Assets/europe_calling_postcard.png",
    width: 533,
    height: 274,
    aspectRatio: 1.9453,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Europe calling postcard",
  },
  "/Assets/Assets/expense_filter_chip.png": {
    path: "/Assets/Assets/expense_filter_chip.png",
    width: 86,
    height: 42,
    aspectRatio: 2.0476,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Expense filter chip",
  },
  "/Assets/Assets/home_loan_house.png": {
    path: "/Assets/Assets/home_loan_house.png",
    width: 364,
    height: 229,
    aspectRatio: 1.5895,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Home loan house",
  },
  "/Assets/Assets/income_filter_chip.png": {
    path: "/Assets/Assets/income_filter_chip.png",
    width: 87,
    height: 42,
    aspectRatio: 2.0714,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Income filter chip",
  },
  "/Assets/Assets/lavender_leaves_decor.png": {
    path: "/Assets/Assets/lavender_leaves_decor.png",
    width: 241,
    height: 292,
    aspectRatio: 0.8253,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Lavender leaves decor",
  },
  "/Assets/Assets/loan_agreement_clipboard.png": {
    path: "/Assets/Assets/loan_agreement_clipboard.png",
    width: 423,
    height: 428,
    aspectRatio: 0.9883,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Loan agreement clipboard",
  },
  "/Assets/Assets/long_term_growth.png": {
    path: "/Assets/Assets/long_term_growth.png",
    width: 442,
    height: 337,
    aspectRatio: 1.3116,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Long term growth",
  },
  "/Assets/Assets/milestone_flag.png": {
    path: "/Assets/Assets/milestone_flag.png",
    width: 242,
    height: 235,
    aspectRatio: 1.0298,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Milestone flag",
  },
  "/Assets/Assets/month_filter_dropdown.png": {
    path: "/Assets/Assets/month_filter_dropdown.png",
    width: 144,
    height: 43,
    aspectRatio: 3.3488,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Month filter dropdown",
  },
  "/Assets/Assets/pay_off_faster_comparison.png": {
    path: "/Assets/Assets/pay_off_faster_comparison.png",
    width: 269,
    height: 284,
    aspectRatio: 0.9472,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Pay off faster comparison",
  },
  "/Assets/Assets/portfolio_allocation.png": {
    path: "/Assets/Assets/portfolio_allocation.png",
    width: 315,
    height: 251,
    aspectRatio: 1.255,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Portfolio allocation",
  },
  "/Assets/Assets/portfolio_performance.png": {
    path: "/Assets/Assets/portfolio_performance.png",
    width: 469,
    height: 166,
    aspectRatio: 2.8253,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Portfolio performance",
  },
  "/Assets/Assets/rupee_receipt_slip.png": {
    path: "/Assets/Assets/rupee_receipt_slip.png",
    width: 264,
    height: 329,
    aspectRatio: 0.8024,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Rupee receipt slip",
  },
  "/Assets/Assets/salary_transaction_row.png": {
    path: "/Assets/Assets/salary_transaction_row.png",
    width: 287,
    height: 67,
    aspectRatio: 4.2836,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Salary transaction row",
  },
  "/Assets/Assets/search_transactions_input.png": {
    path: "/Assets/Assets/search_transactions_input.png",
    width: 309,
    height: 46,
    aspectRatio: 6.7174,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Search transactions input",
  },
  "/Assets/Assets/swiggy_transaction_row.png": {
    path: "/Assets/Assets/swiggy_transaction_row.png",
    width: 285,
    height: 68,
    aspectRatio: 4.1912,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Swiggy transaction row",
  },
  "/Assets/Assets/target_date_calendar.png": {
    path: "/Assets/Assets/target_date_calendar.png",
    width: 310,
    height: 229,
    aspectRatio: 1.3537,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Target date calendar",
  },
  "/Assets/Assets/travel_luggage_passport.png": {
    path: "/Assets/Assets/travel_luggage_passport.png",
    width: 380,
    height: 380,
    aspectRatio: 1.0,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Travel luggage passport",
  },
  "/Assets/Assets/vintage_camera_art.png": {
    path: "/Assets/Assets/vintage_camera_art.png",
    width: 286,
    height: 211,
    aspectRatio: 1.3555,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Vintage camera art",
  },
  "/Assets/Assets/wealth_growth_projection.png": {
    path: "/Assets/Assets/wealth_growth_projection.png",
    width: 430,
    height: 345,
    aspectRatio: 1.2464,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Wealth growth projection",
  },
  "/Assets/Assets/zomato_transaction_row.png": {
    path: "/Assets/Assets/zomato_transaction_row.png",
    width: 285,
    height: 67,
    aspectRatio: 4.2537,
    folder: "Assets",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Zomato transaction row",
  },
  "/Assets/Backgrounds/calendar_date_tile.png": {
    path: "/Assets/Backgrounds/calendar_date_tile.png",
    width: 188,
    height: 247,
    aspectRatio: 0.7611,
    folder: "Backgrounds",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Calendar date tile",
  },
  "/Assets/Backgrounds/eiffel_tower_scenery.png": {
    path: "/Assets/Backgrounds/eiffel_tower_scenery.png",
    width: 426,
    height: 383,
    aspectRatio: 1.1123,
    folder: "Backgrounds",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Eiffel tower scenery",
  },
  "/Assets/Botanical/asset_026.png": {
    path: "/Assets/Botanical/asset_026.png",
    width: 102,
    height: 186,
    aspectRatio: 0.5484,
    folder: "Botanical",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Botanical illustration",
  },
  "/Assets/Botanical/asset_027.png": {
    path: "/Assets/Botanical/asset_027.png",
    width: 95,
    height: 204,
    aspectRatio: 0.4657,
    folder: "Botanical",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Botanical illustration",
  },
  "/Assets/Botanical/asset_028.png": {
    path: "/Assets/Botanical/asset_028.png",
    width: 109,
    height: 189,
    aspectRatio: 0.5767,
    folder: "Botanical",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Botanical illustration",
  },
  "/Assets/Botanical/asset_029.png": {
    path: "/Assets/Botanical/asset_029.png",
    width: 108,
    height: 210,
    aspectRatio: 0.5143,
    folder: "Botanical",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Botanical illustration",
  },
  "/Assets/Cards And Charts/emergency_fund_card.png": {
    path: "/Assets/Cards And Charts/emergency_fund_card.png",
    width: 339,
    height: 213,
    aspectRatio: 1.5915,
    folder: "Cards And Charts",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Emergency fund card",
  },
  "/Assets/Cards And Charts/financial_health_card.png": {
    path: "/Assets/Cards And Charts/financial_health_card.png",
    width: 344,
    height: 190,
    aspectRatio: 1.8105,
    folder: "Cards And Charts",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Financial health card",
  },
  "/Assets/Cards And Charts/monthly_contributions_card.png": {
    path: "/Assets/Cards And Charts/monthly_contributions_card.png",
    width: 335,
    height: 201,
    aspectRatio: 1.6667,
    folder: "Cards And Charts",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Monthly contributions card",
  },
  "/Assets/Cards And Charts/quote_card.png": {
    path: "/Assets/Cards And Charts/quote_card.png",
    width: 187,
    height: 184,
    aspectRatio: 1.0163,
    folder: "Cards And Charts",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Quote card",
  },
  "/Assets/Cards And Charts/savings_goal_card.png": {
    path: "/Assets/Cards And Charts/savings_goal_card.png",
    width: 371,
    height: 211,
    aspectRatio: 1.7583,
    folder: "Cards And Charts",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Savings goal card",
  },
  "/Assets/Cards And Charts/secure_shield.png": {
    path: "/Assets/Cards And Charts/secure_shield.png",
    width: 248,
    height: 232,
    aspectRatio: 1.069,
    folder: "Cards And Charts",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Secure shield",
  },
  "/Assets/Cards And UI/asset_009.png": {
    path: "/Assets/Cards And UI/asset_009.png",
    width: 68,
    height: 20,
    aspectRatio: 3.4,
    folder: "Cards And UI",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards and ui illustration",
  },
  "/Assets/Cards And UI/asset_012.png": {
    path: "/Assets/Cards And UI/asset_012.png",
    width: 70,
    height: 20,
    aspectRatio: 3.5,
    folder: "Cards And UI",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards and ui illustration",
  },
  "/Assets/Cards And UI/at_risk_status.png": {
    path: "/Assets/Cards And UI/at_risk_status.png",
    width: 145,
    height: 64,
    aspectRatio: 2.2656,
    folder: "Cards And UI",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "At risk status",
  },
  "/Assets/Cards And UI/better_fit_status.png": {
    path: "/Assets/Cards And UI/better_fit_status.png",
    width: 157,
    height: 64,
    aspectRatio: 2.4531,
    folder: "Cards And UI",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Better fit status",
  },
  "/Assets/Cards And UI/current_plan_card.png": {
    path: "/Assets/Cards And UI/current_plan_card.png",
    width: 225,
    height: 152,
    aspectRatio: 1.4803,
    folder: "Cards And UI",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Current plan card",
  },
  "/Assets/Cards And UI/emi_impact_chart.png": {
    path: "/Assets/Cards And UI/emi_impact_chart.png",
    width: 228,
    height: 140,
    aspectRatio: 1.6286,
    folder: "Cards And UI",
    purpose: "financial-chart",
    isDecorative: false,
    alt: "Emi impact chart",
  },
  "/Assets/Cards And UI/faster_plan_card.png": {
    path: "/Assets/Cards And UI/faster_plan_card.png",
    width: 221,
    height: 154,
    aspectRatio: 1.4351,
    folder: "Cards And UI",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Faster plan card",
  },
  "/Assets/Cards And UI/good_fit_status.png": {
    path: "/Assets/Cards And UI/good_fit_status.png",
    width: 152,
    height: 64,
    aspectRatio: 2.375,
    folder: "Cards And UI",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Good fit status",
  },
  "/Assets/Cards And UI/interest_impact_chart.png": {
    path: "/Assets/Cards And UI/interest_impact_chart.png",
    width: 207,
    height: 140,
    aspectRatio: 1.4786,
    folder: "Cards And UI",
    purpose: "financial-chart",
    isDecorative: false,
    alt: "Interest impact chart",
  },
  "/Assets/Cards And UI/lower_emi_plan_card.png": {
    path: "/Assets/Cards And UI/lower_emi_plan_card.png",
    width: 219,
    height: 154,
    aspectRatio: 1.4221,
    folder: "Cards And UI",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Lower emi plan card",
  },
  "/Assets/Cards And UI/milestone_calendar_tile.png": {
    path: "/Assets/Cards And UI/milestone_calendar_tile.png",
    width: 266,
    height: 152,
    aspectRatio: 1.75,
    folder: "Cards And UI",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Milestone calendar tile",
  },
  "/Assets/Cards And UI/my_car_goal_card.png": {
    path: "/Assets/Cards And UI/my_car_goal_card.png",
    width: 374,
    height: 214,
    aspectRatio: 1.7477,
    folder: "Cards And UI",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "My car goal card",
  },
  "/Assets/Cards And UI/not_ideal_status.png": {
    path: "/Assets/Cards And UI/not_ideal_status.png",
    width: 154,
    height: 65,
    aspectRatio: 2.3692,
    folder: "Cards And UI",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Not ideal status",
  },
  "/Assets/Cards And UI/total_cost_chart.png": {
    path: "/Assets/Cards And UI/total_cost_chart.png",
    width: 215,
    height: 140,
    aspectRatio: 1.5357,
    folder: "Cards And UI",
    purpose: "financial-chart",
    isDecorative: false,
    alt: "Total cost chart",
  },
  "/Assets/Cards/ai_insight_card.png": {
    path: "/Assets/Cards/ai_insight_card.png",
    width: 280,
    height: 180,
    aspectRatio: 1.5556,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Ai insight card",
  },
  "/Assets/Cards/asset_025.png": {
    path: "/Assets/Cards/asset_025.png",
    width: 332,
    height: 74,
    aspectRatio: 4.4865,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards illustration",
  },
  "/Assets/Cards/asset_030.png": {
    path: "/Assets/Cards/asset_030.png",
    width: 188,
    height: 112,
    aspectRatio: 1.6786,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards illustration",
  },
  "/Assets/Cards/asset_031.png": {
    path: "/Assets/Cards/asset_031.png",
    width: 94,
    height: 110,
    aspectRatio: 0.8545,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards illustration",
  },
  "/Assets/Cards/asset_032.png": {
    path: "/Assets/Cards/asset_032.png",
    width: 158,
    height: 160,
    aspectRatio: 0.9875,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards illustration",
  },
  "/Assets/Cards/asset_033.png": {
    path: "/Assets/Cards/asset_033.png",
    width: 203,
    height: 320,
    aspectRatio: 0.6344,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards illustration",
  },
  "/Assets/Cards/asset_034.png": {
    path: "/Assets/Cards/asset_034.png",
    width: 249,
    height: 133,
    aspectRatio: 1.8722,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards illustration",
  },
  "/Assets/Cards/asset_035.png": {
    path: "/Assets/Cards/asset_035.png",
    width: 124,
    height: 195,
    aspectRatio: 0.6359,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards illustration",
  },
  "/Assets/Cards/asset_036.png": {
    path: "/Assets/Cards/asset_036.png",
    width: 125,
    height: 195,
    aspectRatio: 0.641,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards illustration",
  },
  "/Assets/Cards/asset_037.png": {
    path: "/Assets/Cards/asset_037.png",
    width: 123,
    height: 196,
    aspectRatio: 0.6276,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards illustration",
  },
  "/Assets/Cards/asset_044.png": {
    path: "/Assets/Cards/asset_044.png",
    width: 251,
    height: 178,
    aspectRatio: 1.4101,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Cards illustration",
  },
  "/Assets/Cards/document_summary_card.png": {
    path: "/Assets/Cards/document_summary_card.png",
    width: 490,
    height: 136,
    aspectRatio: 3.6029,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Document summary card",
  },
  "/Assets/Cards/guided_conversation_screen.png": {
    path: "/Assets/Cards/guided_conversation_screen.png",
    width: 342,
    height: 308,
    aspectRatio: 1.1104,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Guided conversation screen",
  },
  "/Assets/Cards/notification_tile.png": {
    path: "/Assets/Cards/notification_tile.png",
    width: 273,
    height: 130,
    aspectRatio: 2.1,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Notification tile",
  },
  "/Assets/Cards/onboarding_step_one.png": {
    path: "/Assets/Cards/onboarding_step_one.png",
    width: 163,
    height: 311,
    aspectRatio: 0.5241,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Onboarding step one",
  },
  "/Assets/Cards/onboarding_step_three.png": {
    path: "/Assets/Cards/onboarding_step_three.png",
    width: 175,
    height: 311,
    aspectRatio: 0.5627,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Onboarding step three",
  },
  "/Assets/Cards/onboarding_step_two.png": {
    path: "/Assets/Cards/onboarding_step_two.png",
    width: 165,
    height: 311,
    aspectRatio: 0.5305,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Onboarding step two",
  },
  "/Assets/Cards/qa_mini_panel.png": {
    path: "/Assets/Cards/qa_mini_panel.png",
    width: 405,
    height: 210,
    aspectRatio: 1.9286,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Qa mini panel",
  },
  "/Assets/Cards/secure_account_setup.png": {
    path: "/Assets/Cards/secure_account_setup.png",
    width: 507,
    height: 257,
    aspectRatio: 1.9728,
    folder: "Cards",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Secure account setup",
  },
  "/Assets/Characters/ai_assistant_headphones.png": {
    path: "/Assets/Characters/ai_assistant_headphones.png",
    width: 188,
    height: 246,
    aspectRatio: 0.7642,
    folder: "Characters",
    purpose: "character-illustration",
    isDecorative: false,
    alt: "Ai assistant headphones",
  },
  "/Assets/Characters/ai_assistant_orb.png": {
    path: "/Assets/Characters/ai_assistant_orb.png",
    width: 213,
    height: 219,
    aspectRatio: 0.9726,
    folder: "Characters",
    purpose: "character-illustration",
    isDecorative: false,
    alt: "Ai assistant orb",
  },
  "/Assets/Characters/asset_010.png": {
    path: "/Assets/Characters/asset_010.png",
    width: 161,
    height: 31,
    aspectRatio: 5.1935,
    folder: "Characters",
    purpose: "character-illustration",
    isDecorative: false,
    alt: "Characters illustration",
  },
  "/Assets/Characters/car_gold_stack.png": {
    path: "/Assets/Characters/car_gold_stack.png",
    width: 155,
    height: 180,
    aspectRatio: 0.8611,
    folder: "Characters",
    purpose: "character-illustration",
    isDecorative: false,
    alt: "Car gold stack",
  },
  "/Assets/Characters/car_in_city_vignette.png": {
    path: "/Assets/Characters/car_in_city_vignette.png",
    width: 629,
    height: 249,
    aspectRatio: 2.5261,
    folder: "Characters",
    purpose: "character-illustration",
    isDecorative: false,
    alt: "Car in city vignette",
  },
  "/Assets/Characters/car_savings_jar.png": {
    path: "/Assets/Characters/car_savings_jar.png",
    width: 246,
    height: 207,
    aspectRatio: 1.1884,
    folder: "Characters",
    purpose: "character-illustration",
    isDecorative: false,
    alt: "Car savings jar",
  },
  "/Assets/Characters/purple_car_front.png": {
    path: "/Assets/Characters/purple_car_front.png",
    width: 380,
    height: 181,
    aspectRatio: 2.0994,
    folder: "Characters",
    purpose: "character-illustration",
    isDecorative: false,
    alt: "Purple car front",
  },
  "/Assets/Characters/purple_car_rear.png": {
    path: "/Assets/Characters/purple_car_rear.png",
    width: 348,
    height: 170,
    aspectRatio: 2.0471,
    folder: "Characters",
    purpose: "character-illustration",
    isDecorative: false,
    alt: "Purple car rear",
  },
  "/Assets/Characters/woman_by_window.png": {
    path: "/Assets/Characters/woman_by_window.png",
    width: 406,
    height: 388,
    aspectRatio: 1.0464,
    folder: "Characters",
    purpose: "character-illustration",
    isDecorative: false,
    alt: "Woman by window",
  },
  "/Assets/Characters/woman_typing_laptop.png": {
    path: "/Assets/Characters/woman_typing_laptop.png",
    width: 301,
    height: 349,
    aspectRatio: 0.8625,
    folder: "Characters",
    purpose: "character-illustration",
    isDecorative: false,
    alt: "Woman typing laptop",
  },
  "/Assets/Characters/woman_with_laptop.png": {
    path: "/Assets/Characters/woman_with_laptop.png",
    width: 395,
    height: 344,
    aspectRatio: 1.1483,
    folder: "Characters",
    purpose: "hero-character",
    isDecorative: false,
    alt: "Woman with laptop",
  },
  "/Assets/Characters/woman_writing_journal.png": {
    path: "/Assets/Characters/woman_writing_journal.png",
    width: 271,
    height: 336,
    aspectRatio: 0.8065,
    folder: "Characters",
    purpose: "character-illustration",
    isDecorative: false,
    alt: "Woman writing journal",
  },
  "/Assets/Charts/asset_010.png": {
    path: "/Assets/Charts/asset_010.png",
    width: 185,
    height: 184,
    aspectRatio: 1.0054,
    folder: "Charts",
    purpose: "financial-chart",
    isDecorative: false,
    alt: "Charts illustration",
  },
  "/Assets/Charts/asset_023.png": {
    path: "/Assets/Charts/asset_023.png",
    width: 222,
    height: 27,
    aspectRatio: 8.2222,
    folder: "Charts",
    purpose: "financial-chart",
    isDecorative: false,
    alt: "Charts illustration",
  },
  "/Assets/Charts/asset_024.png": {
    path: "/Assets/Charts/asset_024.png",
    width: 376,
    height: 269,
    aspectRatio: 1.3978,
    folder: "Charts",
    purpose: "financial-chart",
    isDecorative: false,
    alt: "Charts illustration",
  },
  "/Assets/Charts/asset_043.png": {
    path: "/Assets/Charts/asset_043.png",
    width: 27,
    height: 42,
    aspectRatio: 0.6429,
    folder: "Charts",
    purpose: "financial-chart",
    isDecorative: false,
    alt: "Charts illustration",
  },
  "/Assets/Charts/asset_045.png": {
    path: "/Assets/Charts/asset_045.png",
    width: 26,
    height: 41,
    aspectRatio: 0.6341,
    folder: "Charts",
    purpose: "financial-chart",
    isDecorative: false,
    alt: "Charts illustration",
  },
  "/Assets/Chat/ai_chat_bubble.png": {
    path: "/Assets/Chat/ai_chat_bubble.png",
    width: 269,
    height: 81,
    aspectRatio: 3.321,
    folder: "Chat",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Ai chat bubble",
  },
  "/Assets/Chat/chat_bubble_greeting.png": {
    path: "/Assets/Chat/chat_bubble_greeting.png",
    width: 262,
    height: 84,
    aspectRatio: 3.119,
    folder: "Chat",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Chat bubble greeting",
  },
  "/Assets/Chat/user_chat_bubble.png": {
    path: "/Assets/Chat/user_chat_bubble.png",
    width: 264,
    height: 77,
    aspectRatio: 3.4286,
    folder: "Chat",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "User chat bubble",
  },
  "/Assets/Effects/blue_watercolor_stroke.png": {
    path: "/Assets/Effects/blue_watercolor_stroke.png",
    width: 208,
    height: 71,
    aspectRatio: 2.9296,
    folder: "Effects",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Blue watercolor stroke",
  },
  "/Assets/Effects/green_watercolor_stroke.png": {
    path: "/Assets/Effects/green_watercolor_stroke.png",
    width: 185,
    height: 72,
    aspectRatio: 2.5694,
    folder: "Effects",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Green watercolor stroke",
  },
  "/Assets/Effects/purple_watercolor_stroke.png": {
    path: "/Assets/Effects/purple_watercolor_stroke.png",
    width: 197,
    height: 73,
    aspectRatio: 2.6986,
    folder: "Effects",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Purple watercolor stroke",
  },
  "/Assets/Effects/watercolor_cloud.png": {
    path: "/Assets/Effects/watercolor_cloud.png",
    width: 75,
    height: 59,
    aspectRatio: 1.2712,
    folder: "Effects",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Watercolor cloud",
  },
  "/Assets/Effects/watercolor_cloud_blue.png": {
    path: "/Assets/Effects/watercolor_cloud_blue.png",
    width: 127,
    height: 60,
    aspectRatio: 2.1167,
    folder: "Effects",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Watercolor cloud blue",
  },
  "/Assets/Effects/watercolor_cloud_cyan.png": {
    path: "/Assets/Effects/watercolor_cloud_cyan.png",
    width: 160,
    height: 56,
    aspectRatio: 2.8571,
    folder: "Effects",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Watercolor cloud cyan",
  },
  "/Assets/Effects/watercolor_splash_orange.png": {
    path: "/Assets/Effects/watercolor_splash_orange.png",
    width: 140,
    height: 52,
    aspectRatio: 2.6923,
    folder: "Effects",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Watercolor splash orange",
  },
  "/Assets/Elements/asset_026.png": {
    path: "/Assets/Elements/asset_026.png",
    width: 38,
    height: 45,
    aspectRatio: 0.8444,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Elements illustration",
  },
  "/Assets/Elements/blue_watercolor_stripe.png": {
    path: "/Assets/Elements/blue_watercolor_stripe.png",
    width: 151,
    height: 61,
    aspectRatio: 2.4754,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Blue watercolor stripe",
  },
  "/Assets/Elements/dotted_path_arrow.png": {
    path: "/Assets/Elements/dotted_path_arrow.png",
    width: 305,
    height: 117,
    aspectRatio: 2.6068,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Dotted path arrow",
  },
  "/Assets/Elements/gold_watercolor_stripe.png": {
    path: "/Assets/Elements/gold_watercolor_stripe.png",
    width: 138,
    height: 60,
    aspectRatio: 2.3,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Gold watercolor stripe",
  },
  "/Assets/Elements/lavender_plant_decor.png": {
    path: "/Assets/Elements/lavender_plant_decor.png",
    width: 118,
    height: 116,
    aspectRatio: 1.0172,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Lavender plant decor",
  },
  "/Assets/Elements/leaf_branch_four.png": {
    path: "/Assets/Elements/leaf_branch_four.png",
    width: 86,
    height: 99,
    aspectRatio: 0.8687,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Leaf branch four",
  },
  "/Assets/Elements/leaf_branch_one.png": {
    path: "/Assets/Elements/leaf_branch_one.png",
    width: 47,
    height: 86,
    aspectRatio: 0.5465,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Leaf branch one",
  },
  "/Assets/Elements/leaf_branch_three.png": {
    path: "/Assets/Elements/leaf_branch_three.png",
    width: 56,
    height: 87,
    aspectRatio: 0.6437,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Leaf branch three",
  },
  "/Assets/Elements/leaf_branch_two.png": {
    path: "/Assets/Elements/leaf_branch_two.png",
    width: 77,
    height: 74,
    aspectRatio: 1.0405,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Leaf branch two",
  },
  "/Assets/Elements/purple_watercolor_stroke.png": {
    path: "/Assets/Elements/purple_watercolor_stroke.png",
    width: 163,
    height: 64,
    aspectRatio: 2.5469,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Purple watercolor stroke",
  },
  "/Assets/Elements/small_blue_icon_element.png": {
    path: "/Assets/Elements/small_blue_icon_element.png",
    width: 343,
    height: 196,
    aspectRatio: 1.75,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Small blue icon element",
  },
  "/Assets/Elements/teal_watercolor_stroke.png": {
    path: "/Assets/Elements/teal_watercolor_stroke.png",
    width: 155,
    height: 59,
    aspectRatio: 2.6271,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Teal watercolor stroke",
  },
  "/Assets/Elements/watercolor_brush_stroke.png": {
    path: "/Assets/Elements/watercolor_brush_stroke.png",
    width: 231,
    height: 117,
    aspectRatio: 1.9744,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Watercolor brush stroke",
  },
  "/Assets/Elements/watercolor_cloud.png": {
    path: "/Assets/Elements/watercolor_cloud.png",
    width: 246,
    height: 127,
    aspectRatio: 1.937,
    folder: "Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Watercolor cloud",
  },
  "/Assets/Finance UI/affordability_score.png": {
    path: "/Assets/Finance UI/affordability_score.png",
    width: 229,
    height: 234,
    aspectRatio: 0.9786,
    folder: "Finance UI",
    purpose: "financial-metric-preview",
    isDecorative: false,
    alt: "Affordability score",
  },
  "/Assets/Finance UI/cash_bundles_coins.png": {
    path: "/Assets/Finance UI/cash_bundles_coins.png",
    width: 237,
    height: 148,
    aspectRatio: 1.6014,
    folder: "Finance UI",
    purpose: "financial-metric-preview",
    isDecorative: false,
    alt: "Cash bundles coins",
  },
  "/Assets/Finance UI/down_payment_goal.png": {
    path: "/Assets/Finance UI/down_payment_goal.png",
    width: 446,
    height: 180,
    aspectRatio: 2.4778,
    folder: "Finance UI",
    purpose: "financial-metric-preview",
    isDecorative: false,
    alt: "Down payment goal",
  },
  "/Assets/Finance UI/home_goal_progress.png": {
    path: "/Assets/Finance UI/home_goal_progress.png",
    width: 448,
    height: 161,
    aspectRatio: 2.7826,
    folder: "Finance UI",
    purpose: "financial-metric-preview",
    isDecorative: false,
    alt: "Home goal progress",
  },
  "/Assets/Finance UI/target_closing_date.png": {
    path: "/Assets/Finance UI/target_closing_date.png",
    width: 314,
    height: 320,
    aspectRatio: 0.9812,
    folder: "Finance UI",
    purpose: "financial-metric-preview",
    isDecorative: false,
    alt: "Target closing date",
  },
  "/Assets/Houses/cozy_first_home.png": {
    path: "/Assets/Houses/cozy_first_home.png",
    width: 384,
    height: 331,
    aspectRatio: 1.1601,
    folder: "Houses",
    purpose: "housing-goal",
    isDecorative: false,
    alt: "Cozy first home",
  },
  "/Assets/Houses/premium_home.png": {
    path: "/Assets/Houses/premium_home.png",
    width: 523,
    height: 336,
    aspectRatio: 1.5565,
    folder: "Houses",
    purpose: "housing-goal",
    isDecorative: false,
    alt: "Premium home",
  },
  "/Assets/Houses/savings_jar_home.png": {
    path: "/Assets/Houses/savings_jar_home.png",
    width: 365,
    height: 202,
    aspectRatio: 1.8069,
    folder: "Houses",
    purpose: "housing-goal",
    isDecorative: false,
    alt: "Savings jar home",
  },
  "/Assets/Icons And Misc/brush_stroke.png": {
    path: "/Assets/Icons And Misc/brush_stroke.png",
    width: 179,
    height: 51,
    aspectRatio: 3.5098,
    folder: "Icons And Misc",
    purpose: "icon",
    isDecorative: true,
    alt: "Brush stroke",
  },
  "/Assets/Icons And Misc/house_key_ring.png": {
    path: "/Assets/Icons And Misc/house_key_ring.png",
    width: 235,
    height: 204,
    aspectRatio: 1.152,
    folder: "Icons And Misc",
    purpose: "icon",
    isDecorative: true,
    alt: "House key ring",
  },
  "/Assets/Icons And Misc/purple_heart.png": {
    path: "/Assets/Icons And Misc/purple_heart.png",
    width: 60,
    height: 61,
    aspectRatio: 0.9836,
    folder: "Icons And Misc",
    purpose: "icon",
    isDecorative: true,
    alt: "Purple heart",
  },
  "/Assets/Icons And Misc/shield_protection.png": {
    path: "/Assets/Icons And Misc/shield_protection.png",
    width: 250,
    height: 180,
    aspectRatio: 1.3889,
    folder: "Icons And Misc",
    purpose: "icon",
    isDecorative: true,
    alt: "Shield protection",
  },
  "/Assets/Icons/asset_002.png": {
    path: "/Assets/Icons/asset_002.png",
    width: 75,
    height: 73,
    aspectRatio: 1.0274,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_003.png": {
    path: "/Assets/Icons/asset_003.png",
    width: 75,
    height: 73,
    aspectRatio: 1.0274,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_004.png": {
    path: "/Assets/Icons/asset_004.png",
    width: 65,
    height: 67,
    aspectRatio: 0.9701,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_005.png": {
    path: "/Assets/Icons/asset_005.png",
    width: 56,
    height: 65,
    aspectRatio: 0.8615,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_006.png": {
    path: "/Assets/Icons/asset_006.png",
    width: 57,
    height: 65,
    aspectRatio: 0.8769,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_014.png": {
    path: "/Assets/Icons/asset_014.png",
    width: 74,
    height: 73,
    aspectRatio: 1.0137,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_015.png": {
    path: "/Assets/Icons/asset_015.png",
    width: 75,
    height: 74,
    aspectRatio: 1.0135,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_016.png": {
    path: "/Assets/Icons/asset_016.png",
    width: 75,
    height: 73,
    aspectRatio: 1.0274,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_017.png": {
    path: "/Assets/Icons/asset_017.png",
    width: 66,
    height: 69,
    aspectRatio: 0.9565,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_018.png": {
    path: "/Assets/Icons/asset_018.png",
    width: 66,
    height: 20,
    aspectRatio: 3.3,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_018_2.png": {
    path: "/Assets/Icons/asset_018_2.png",
    width: 58,
    height: 65,
    aspectRatio: 0.8923,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration 2",
  },
  "/Assets/Icons/asset_019.png": {
    path: "/Assets/Icons/asset_019.png",
    width: 31,
    height: 20,
    aspectRatio: 1.55,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_019_2.png": {
    path: "/Assets/Icons/asset_019_2.png",
    width: 57,
    height: 65,
    aspectRatio: 0.8769,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration 2",
  },
  "/Assets/Icons/asset_038.png": {
    path: "/Assets/Icons/asset_038.png",
    width: 22,
    height: 27,
    aspectRatio: 0.8148,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_039.png": {
    path: "/Assets/Icons/asset_039.png",
    width: 34,
    height: 38,
    aspectRatio: 0.8947,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_040.png": {
    path: "/Assets/Icons/asset_040.png",
    width: 27,
    height: 30,
    aspectRatio: 0.9,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_041.png": {
    path: "/Assets/Icons/asset_041.png",
    width: 20,
    height: 22,
    aspectRatio: 0.9091,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/asset_042.png": {
    path: "/Assets/Icons/asset_042.png",
    width: 25,
    height: 29,
    aspectRatio: 0.8621,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Icons illustration",
  },
  "/Assets/Icons/car_key_icon.png": {
    path: "/Assets/Icons/car_key_icon.png",
    width: 123,
    height: 166,
    aspectRatio: 0.741,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Car key icon",
  },
  "/Assets/Icons/spark_research_icon.png": {
    path: "/Assets/Icons/spark_research_icon.png",
    width: 125,
    height: 120,
    aspectRatio: 1.0417,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Spark research icon",
  },
  "/Assets/Icons/steering_wheel_icon.png": {
    path: "/Assets/Icons/steering_wheel_icon.png",
    width: 143,
    height: 152,
    aspectRatio: 0.9408,
    folder: "Icons",
    purpose: "icon",
    isDecorative: true,
    alt: "Steering wheel icon",
  },
  "/Assets/Jars And Coins/coins_and_sparkles.png": {
    path: "/Assets/Jars And Coins/coins_and_sparkles.png",
    width: 164,
    height: 168,
    aspectRatio: 0.9762,
    folder: "Jars And Coins",
    purpose: "savings-goal",
    isDecorative: false,
    alt: "Coins and sparkles",
  },
  "/Assets/Jars And Coins/coins_in_jar.png": {
    path: "/Assets/Jars And Coins/coins_in_jar.png",
    width: 211,
    height: 232,
    aspectRatio: 0.9095,
    folder: "Jars And Coins",
    purpose: "savings-goal",
    isDecorative: false,
    alt: "Coins in jar",
  },
  "/Assets/Jars And Coins/plant_in_jar.png": {
    path: "/Assets/Jars And Coins/plant_in_jar.png",
    width: 200,
    height: 227,
    aspectRatio: 0.8811,
    folder: "Jars And Coins",
    purpose: "savings-goal",
    isDecorative: false,
    alt: "Plant in jar",
  },
  "/Assets/Nature And Accents/asset_016.png": {
    path: "/Assets/Nature And Accents/asset_016.png",
    width: 24,
    height: 28,
    aspectRatio: 0.8571,
    folder: "Nature And Accents",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Nature and accents illustration",
  },
  "/Assets/Nature And Accents/leafy_branch.png": {
    path: "/Assets/Nature And Accents/leafy_branch.png",
    width: 169,
    height: 229,
    aspectRatio: 0.738,
    folder: "Nature And Accents",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Leafy branch",
  },
  "/Assets/Nature And Accents/sparkle_accent.png": {
    path: "/Assets/Nature And Accents/sparkle_accent.png",
    width: 22,
    height: 27,
    aspectRatio: 0.8148,
    folder: "Nature And Accents",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Sparkle accent",
  },
  "/Assets/Nature Elements/green_leaves.png": {
    path: "/Assets/Nature Elements/green_leaves.png",
    width: 66,
    height: 128,
    aspectRatio: 0.5156,
    folder: "Nature Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Green leaves",
  },
  "/Assets/Nature Elements/lavender_branch.png": {
    path: "/Assets/Nature Elements/lavender_branch.png",
    width: 59,
    height: 154,
    aspectRatio: 0.3831,
    folder: "Nature Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Lavender branch",
  },
  "/Assets/Nature Elements/leafy_twig.png": {
    path: "/Assets/Nature Elements/leafy_twig.png",
    width: 76,
    height: 145,
    aspectRatio: 0.5241,
    folder: "Nature Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Leafy twig",
  },
  "/Assets/Nature Elements/mountain_landscape.png": {
    path: "/Assets/Nature Elements/mountain_landscape.png",
    width: 281,
    height: 361,
    aspectRatio: 0.7784,
    folder: "Nature Elements",
    purpose: "brand-accent",
    isDecorative: true,
    alt: "Mountain landscape",
  },
  "/Assets/Objects/beach_chair_sea.png": {
    path: "/Assets/Objects/beach_chair_sea.png",
    width: 538,
    height: 237,
    aspectRatio: 2.27,
    folder: "Objects",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Beach chair sea",
  },
  "/Assets/Objects/ceramic_mug.png": {
    path: "/Assets/Objects/ceramic_mug.png",
    width: 171,
    height: 156,
    aspectRatio: 1.0962,
    folder: "Objects",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Ceramic mug",
  },
  "/Assets/Objects/coin_stacks.png": {
    path: "/Assets/Objects/coin_stacks.png",
    width: 262,
    height: 216,
    aspectRatio: 1.213,
    folder: "Objects",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Coin stacks",
  },
  "/Assets/Objects/mountain_landscape.png": {
    path: "/Assets/Objects/mountain_landscape.png",
    width: 351,
    height: 242,
    aspectRatio: 1.4504,
    folder: "Objects",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Mountain landscape",
  },
  "/Assets/Objects/potted_plant.png": {
    path: "/Assets/Objects/potted_plant.png",
    width: 189,
    height: 245,
    aspectRatio: 0.7714,
    folder: "Objects",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Potted plant",
  },
  "/Assets/Objects/scenic_window_view.png": {
    path: "/Assets/Objects/scenic_window_view.png",
    width: 322,
    height: 294,
    aspectRatio: 1.0952,
    folder: "Objects",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Scenic window view",
  },
  "/Assets/Objects/stacked_books.png": {
    path: "/Assets/Objects/stacked_books.png",
    width: 273,
    height: 186,
    aspectRatio: 1.4677,
    folder: "Objects",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Stacked books",
  },
  "/Assets/Objects/stacked_coins_pile.png": {
    path: "/Assets/Objects/stacked_coins_pile.png",
    width: 22,
    height: 25,
    aspectRatio: 0.88,
    folder: "Objects",
    purpose: "product-artifact",
    isDecorative: false,
    alt: "Stacked coins pile",
  },
  "/Assets/Palettes/asset_046.png": {
    path: "/Assets/Palettes/asset_046.png",
    width: 78,
    height: 54,
    aspectRatio: 1.4444,
    folder: "Palettes",
    purpose: "palette-swatch",
    isDecorative: true,
    alt: "Palettes illustration",
  },
  "/Assets/Palettes/asset_047.png": {
    path: "/Assets/Palettes/asset_047.png",
    width: 81,
    height: 54,
    aspectRatio: 1.5,
    folder: "Palettes",
    purpose: "palette-swatch",
    isDecorative: true,
    alt: "Palettes illustration",
  },
  "/Assets/Palettes/asset_048.png": {
    path: "/Assets/Palettes/asset_048.png",
    width: 79,
    height: 54,
    aspectRatio: 1.463,
    folder: "Palettes",
    purpose: "palette-swatch",
    isDecorative: true,
    alt: "Palettes illustration",
  },
  "/Assets/Palettes/asset_049.png": {
    path: "/Assets/Palettes/asset_049.png",
    width: 78,
    height: 54,
    aspectRatio: 1.4444,
    folder: "Palettes",
    purpose: "palette-swatch",
    isDecorative: true,
    alt: "Palettes illustration",
  },
  "/Assets/Palettes/asset_050.png": {
    path: "/Assets/Palettes/asset_050.png",
    width: 77,
    height: 54,
    aspectRatio: 1.4259,
    folder: "Palettes",
    purpose: "palette-swatch",
    isDecorative: true,
    alt: "Palettes illustration",
  },
  "/Assets/Palettes/asset_051.png": {
    path: "/Assets/Palettes/asset_051.png",
    width: 76,
    height: 55,
    aspectRatio: 1.3818,
    folder: "Palettes",
    purpose: "palette-swatch",
    isDecorative: true,
    alt: "Palettes illustration",
  },
  "/Assets/Palettes/asset_052.png": {
    path: "/Assets/Palettes/asset_052.png",
    width: 77,
    height: 55,
    aspectRatio: 1.4,
    folder: "Palettes",
    purpose: "palette-swatch",
    isDecorative: true,
    alt: "Palettes illustration",
  },
  "/Assets/Palettes/asset_053.png": {
    path: "/Assets/Palettes/asset_053.png",
    width: 75,
    height: 55,
    aspectRatio: 1.3636,
    folder: "Palettes",
    purpose: "palette-swatch",
    isDecorative: true,
    alt: "Palettes illustration",
  },
  "/Assets/Piggy Banks/graduate_piggy_bank.png": {
    path: "/Assets/Piggy Banks/graduate_piggy_bank.png",
    width: 250,
    height: 274,
    aspectRatio: 0.9124,
    folder: "Piggy Banks",
    purpose: "savings-goal",
    isDecorative: false,
    alt: "Graduate piggy bank",
  },
  "/Assets/Piggy Banks/piggy_bank_coin.png": {
    path: "/Assets/Piggy Banks/piggy_bank_coin.png",
    width: 274,
    height: 266,
    aspectRatio: 1.0301,
    folder: "Piggy Banks",
    purpose: "savings-goal",
    isDecorative: false,
    alt: "Piggy bank coin",
  },
  "/Assets/Piggy Banks/piggy_bank_stack.png": {
    path: "/Assets/Piggy Banks/piggy_bank_stack.png",
    width: 272,
    height: 210,
    aspectRatio: 1.2952,
    folder: "Piggy Banks",
    purpose: "savings-goal",
    isDecorative: false,
    alt: "Piggy bank stack",
  },
  "/Assets/Status/asset_007.png": {
    path: "/Assets/Status/asset_007.png",
    width: 113,
    height: 43,
    aspectRatio: 2.6279,
    folder: "Status",
    purpose: "status-indicator",
    isDecorative: true,
    alt: "Status illustration",
  },
  "/Assets/Status/asset_008.png": {
    path: "/Assets/Status/asset_008.png",
    width: 102,
    height: 43,
    aspectRatio: 2.3721,
    folder: "Status",
    purpose: "status-indicator",
    isDecorative: true,
    alt: "Status illustration",
  },
  "/Assets/Status/asset_009.png": {
    path: "/Assets/Status/asset_009.png",
    width: 107,
    height: 43,
    aspectRatio: 2.4884,
    folder: "Status",
    purpose: "status-indicator",
    isDecorative: true,
    alt: "Status illustration",
  },
  "/Assets/Status/asset_011.png": {
    path: "/Assets/Status/asset_011.png",
    width: 102,
    height: 42,
    aspectRatio: 2.4286,
    folder: "Status",
    purpose: "status-indicator",
    isDecorative: true,
    alt: "Status illustration",
  },
  "/Assets/Status/asset_012.png": {
    path: "/Assets/Status/asset_012.png",
    width: 142,
    height: 43,
    aspectRatio: 3.3023,
    folder: "Status",
    purpose: "status-indicator",
    isDecorative: true,
    alt: "Status illustration",
  },
  "/Assets/Status/asset_013.png": {
    path: "/Assets/Status/asset_013.png",
    width: 110,
    height: 43,
    aspectRatio: 2.5581,
    folder: "Status",
    purpose: "status-indicator",
    isDecorative: true,
    alt: "Status illustration",
  },
  "/Assets/Status/asset_020.png": {
    path: "/Assets/Status/asset_020.png",
    width: 109,
    height: 44,
    aspectRatio: 2.4773,
    folder: "Status",
    purpose: "status-indicator",
    isDecorative: true,
    alt: "Status illustration",
  },
  "/Assets/Status/asset_021.png": {
    path: "/Assets/Status/asset_021.png",
    width: 112,
    height: 43,
    aspectRatio: 2.6047,
    folder: "Status",
    purpose: "status-indicator",
    isDecorative: true,
    alt: "Status illustration",
  },
  "/Assets/Status/asset_022.png": {
    path: "/Assets/Status/asset_022.png",
    width: 90,
    height: 43,
    aspectRatio: 2.093,
    folder: "Status",
    purpose: "status-indicator",
    isDecorative: true,
    alt: "Status illustration",
  },
  "/Assets/UI/amazon_icon_circle.png": {
    path: "/Assets/UI/amazon_icon_circle.png",
    width: 77,
    height: 78,
    aspectRatio: 0.9872,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Amazon icon circle",
  },
  "/Assets/UI/bag_icon_circle.png": {
    path: "/Assets/UI/bag_icon_circle.png",
    width: 77,
    height: 79,
    aspectRatio: 0.9747,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Bag icon circle",
  },
  "/Assets/UI/beige_circle.png": {
    path: "/Assets/UI/beige_circle.png",
    width: 90,
    height: 91,
    aspectRatio: 0.989,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Beige circle",
  },
  "/Assets/UI/category_breakdown_card.png": {
    path: "/Assets/UI/category_breakdown_card.png",
    width: 283,
    height: 240,
    aspectRatio: 1.1792,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Category breakdown card",
  },
  "/Assets/UI/clear_filter_button.png": {
    path: "/Assets/UI/clear_filter_button.png",
    width: 63,
    height: 41,
    aspectRatio: 1.5366,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Clear filter button",
  },
  "/Assets/UI/credit_card_bill.png": {
    path: "/Assets/UI/credit_card_bill.png",
    width: 359,
    height: 307,
    aspectRatio: 1.1694,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Credit card bill",
  },
  "/Assets/UI/dark_circle.png": {
    path: "/Assets/UI/dark_circle.png",
    width: 89,
    height: 90,
    aspectRatio: 0.9889,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Dark circle",
  },
  "/Assets/UI/debt_free_badge.png": {
    path: "/Assets/UI/debt_free_badge.png",
    width: 236,
    height: 280,
    aspectRatio: 0.8429,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Debt free badge",
  },
  "/Assets/UI/debt_payoff_progress.png": {
    path: "/Assets/UI/debt_payoff_progress.png",
    width: 279,
    height: 389,
    aspectRatio: 0.7172,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Debt payoff progress",
  },
  "/Assets/UI/debt_trend_chart.png": {
    path: "/Assets/UI/debt_trend_chart.png",
    width: 572,
    height: 222,
    aspectRatio: 2.5766,
    folder: "UI",
    purpose: "financial-chart",
    isDecorative: false,
    alt: "Debt trend chart",
  },
  "/Assets/UI/dotted_arrow_line.png": {
    path: "/Assets/UI/dotted_arrow_line.png",
    width: 421,
    height: 98,
    aspectRatio: 4.2959,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Dotted arrow line",
  },
  "/Assets/UI/emergency_fund_card.png": {
    path: "/Assets/UI/emergency_fund_card.png",
    width: 421,
    height: 235,
    aspectRatio: 1.7915,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Emergency fund card",
  },
  "/Assets/UI/europe_trip_progress.png": {
    path: "/Assets/UI/europe_trip_progress.png",
    width: 409,
    height: 263,
    aspectRatio: 1.5551,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Europe trip progress",
  },
  "/Assets/UI/financial_health_card.png": {
    path: "/Assets/UI/financial_health_card.png",
    width: 294,
    height: 230,
    aspectRatio: 1.2783,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Financial health card",
  },
  "/Assets/UI/fuel_icon_circle.png": {
    path: "/Assets/UI/fuel_icon_circle.png",
    width: 78,
    height: 79,
    aspectRatio: 0.9873,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Fuel icon circle",
  },
  "/Assets/UI/goal_progress_widget.png": {
    path: "/Assets/UI/goal_progress_widget.png",
    width: 365,
    height: 262,
    aspectRatio: 1.3931,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Goal progress widget",
  },
  "/Assets/UI/green_circle.png": {
    path: "/Assets/UI/green_circle.png",
    width: 90,
    height: 91,
    aspectRatio: 0.989,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Green circle",
  },
  "/Assets/UI/growth_arrow.png": {
    path: "/Assets/UI/growth_arrow.png",
    width: 179,
    height: 111,
    aspectRatio: 1.6126,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Growth arrow",
  },
  "/Assets/UI/light_blue_circle.png": {
    path: "/Assets/UI/light_blue_circle.png",
    width: 90,
    height: 91,
    aspectRatio: 0.989,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Light blue circle",
  },
  "/Assets/UI/money_jar_savings.png": {
    path: "/Assets/UI/money_jar_savings.png",
    width: 277,
    height: 281,
    aspectRatio: 0.9858,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Money jar savings",
  },
  "/Assets/UI/monthly_budget_card.png": {
    path: "/Assets/UI/monthly_budget_card.png",
    width: 328,
    height: 209,
    aspectRatio: 1.5694,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Monthly budget card",
  },
  "/Assets/UI/monthly_emi_card.png": {
    path: "/Assets/UI/monthly_emi_card.png",
    width: 442,
    height: 213,
    aspectRatio: 2.0751,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Monthly emi card",
  },
  "/Assets/UI/monthly_outlook_card.png": {
    path: "/Assets/UI/monthly_outlook_card.png",
    width: 391,
    height: 240,
    aspectRatio: 1.6292,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Monthly outlook card",
  },
  "/Assets/UI/more_icon_circle.png": {
    path: "/Assets/UI/more_icon_circle.png",
    width: 79,
    height: 79,
    aspectRatio: 1.0,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "More icon circle",
  },
  "/Assets/UI/net_worth_dashboard.png": {
    path: "/Assets/UI/net_worth_dashboard.png",
    width: 429,
    height: 259,
    aspectRatio: 1.6564,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Net worth dashboard",
  },
  "/Assets/UI/outline_chart.png": {
    path: "/Assets/UI/outline_chart.png",
    width: 76,
    height: 64,
    aspectRatio: 1.1875,
    folder: "UI",
    purpose: "financial-chart",
    isDecorative: false,
    alt: "Outline chart",
  },
  "/Assets/UI/outline_jar.png": {
    path: "/Assets/UI/outline_jar.png",
    width: 63,
    height: 86,
    aspectRatio: 0.7326,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Outline jar",
  },
  "/Assets/UI/outline_piggy_bank.png": {
    path: "/Assets/UI/outline_piggy_bank.png",
    width: 94,
    height: 88,
    aspectRatio: 1.0682,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Outline piggy bank",
  },
  "/Assets/UI/outline_plant.png": {
    path: "/Assets/UI/outline_plant.png",
    width: 58,
    height: 86,
    aspectRatio: 0.6744,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Outline plant",
  },
  "/Assets/UI/outline_shield.png": {
    path: "/Assets/UI/outline_shield.png",
    width: 70,
    height: 87,
    aspectRatio: 0.8046,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Outline shield",
  },
  "/Assets/UI/outstanding_balance_card.png": {
    path: "/Assets/UI/outstanding_balance_card.png",
    width: 281,
    height: 382,
    aspectRatio: 0.7356,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Outstanding balance card",
  },
  "/Assets/UI/pale_blue_circle.png": {
    path: "/Assets/UI/pale_blue_circle.png",
    width: 90,
    height: 91,
    aspectRatio: 0.989,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Pale blue circle",
  },
  "/Assets/UI/purple_circle.png": {
    path: "/Assets/UI/purple_circle.png",
    width: 88,
    height: 91,
    aspectRatio: 0.967,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Purple circle",
  },
  "/Assets/UI/purple_watercolor_banner.png": {
    path: "/Assets/UI/purple_watercolor_banner.png",
    width: 497,
    height: 104,
    aspectRatio: 4.7788,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Purple watercolor banner",
  },
  "/Assets/UI/security_shield_icon.png": {
    path: "/Assets/UI/security_shield_icon.png",
    width: 306,
    height: 227,
    aspectRatio: 1.348,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Security shield icon",
  },
  "/Assets/UI/shopping_icon_circle.png": {
    path: "/Assets/UI/shopping_icon_circle.png",
    width: 77,
    height: 78,
    aspectRatio: 0.9872,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Shopping icon circle",
  },
  "/Assets/UI/sip_in_progress.png": {
    path: "/Assets/UI/sip_in_progress.png",
    width: 411,
    height: 324,
    aspectRatio: 1.2685,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Sip in progress",
  },
  "/Assets/UI/sparkle_badge.png": {
    path: "/Assets/UI/sparkle_badge.png",
    width: 230,
    height: 158,
    aspectRatio: 1.4557,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Sparkle badge",
  },
  "/Assets/UI/sparkle_icon.png": {
    path: "/Assets/UI/sparkle_icon.png",
    width: 20,
    height: 22,
    aspectRatio: 0.9091,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Sparkle icon",
  },
  "/Assets/UI/sparkle_icon_blue.png": {
    path: "/Assets/UI/sparkle_icon_blue.png",
    width: 32,
    height: 36,
    aspectRatio: 0.8889,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Sparkle icon blue",
  },
  "/Assets/UI/sparkle_icon_outlined.png": {
    path: "/Assets/UI/sparkle_icon_outlined.png",
    width: 25,
    height: 27,
    aspectRatio: 0.9259,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Sparkle icon outlined",
  },
  "/Assets/UI/sparkle_icon_purple.png": {
    path: "/Assets/UI/sparkle_icon_purple.png",
    width: 21,
    height: 24,
    aspectRatio: 0.875,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Sparkle icon purple",
  },
  "/Assets/UI/spending_insights_chart.png": {
    path: "/Assets/UI/spending_insights_chart.png",
    width: 288,
    height: 207,
    aspectRatio: 1.3913,
    folder: "UI",
    purpose: "financial-chart",
    isDecorative: false,
    alt: "Spending insights chart",
  },
  "/Assets/UI/spending_snapshot_card.png": {
    path: "/Assets/UI/spending_snapshot_card.png",
    width: 365,
    height: 236,
    aspectRatio: 1.5466,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Spending snapshot card",
  },
  "/Assets/UI/swiggy_icon_circle.png": {
    path: "/Assets/UI/swiggy_icon_circle.png",
    width: 77,
    height: 78,
    aspectRatio: 0.9872,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Swiggy icon circle",
  },
  "/Assets/UI/transport_icon_circle.png": {
    path: "/Assets/UI/transport_icon_circle.png",
    width: 77,
    height: 79,
    aspectRatio: 0.9747,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Transport icon circle",
  },
  "/Assets/UI/travel_icon_circle.png": {
    path: "/Assets/UI/travel_icon_circle.png",
    width: 80,
    height: 79,
    aspectRatio: 1.0127,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Travel icon circle",
  },
  "/Assets/UI/trip_budget_widget.png": {
    path: "/Assets/UI/trip_budget_widget.png",
    width: 307,
    height: 229,
    aspectRatio: 1.3406,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Trip budget widget",
  },
  "/Assets/UI/wallet_icon.png": {
    path: "/Assets/UI/wallet_icon.png",
    width: 74,
    height: 73,
    aspectRatio: 1.0137,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Wallet icon",
  },
  "/Assets/UI/wallet_illustration.png": {
    path: "/Assets/UI/wallet_illustration.png",
    width: 368,
    height: 314,
    aspectRatio: 1.172,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Wallet illustration",
  },
  "/Assets/UI/zomato_icon_circle.png": {
    path: "/Assets/UI/zomato_icon_circle.png",
    width: 77,
    height: 78,
    aspectRatio: 0.9872,
    folder: "UI",
    purpose: "ui-widget",
    isDecorative: false,
    alt: "Zomato icon circle",
  },
};

export const ALL_ASSETS: AssetMetadata[] = Object.values(ASSET_REGISTRY);

export function getAsset(path: string): AssetMetadata | undefined {
  return ASSET_REGISTRY[path];
}

export function getAssetsByFolder(folder: string): AssetMetadata[] {
  const f = folder.toLowerCase();
  return ALL_ASSETS.filter((item) => item.folder.toLowerCase() === f);
}

export function getAssetsByPurpose(purpose: AssetPurpose): AssetMetadata[] {
  return ALL_ASSETS.filter((item) => item.purpose === purpose);
}

// Canonical Named Assets for Direct Import
export const ASSET_WOMAN_WITH_LAPTOP = ASSET_REGISTRY["/Assets/Characters/woman_with_laptop.png"];
export const ASSET_SAVINGS_JAR_HOME = ASSET_REGISTRY["/Assets/Houses/savings_jar_home.png"];
export const ASSET_COZY_FIRST_HOME = ASSET_REGISTRY["/Assets/Houses/cozy_first_home.png"];
export const ASSET_PREMIUM_HOME = ASSET_REGISTRY["/Assets/Houses/premium_home.png"];
export const ASSET_EUROPE_TRIP = ASSET_REGISTRY["/Assets/UI/europe_trip_progress.png"];
export const ASSET_DEBT_PAYOFF = ASSET_REGISTRY["/Assets/UI/debt_payoff_progress.png"];
export const ASSET_MONTHLY_OUTLOOK = ASSET_REGISTRY["/Assets/UI/monthly_outlook_card.png"];
export const ASSET_NET_WORTH_DASHBOARD = ASSET_REGISTRY["/Assets/UI/net_worth_dashboard.png"];
export const ASSET_SPENDING_INSIGHTS = ASSET_REGISTRY["/Assets/UI/spending_insights_chart.png"];
export const ASSET_AFFORDABILITY_SCORE = ASSET_REGISTRY["/Assets/Finance UI/affordability_score.png"];
export const ASSET_DOWN_PAYMENT_GOAL = ASSET_REGISTRY["/Assets/Finance UI/down_payment_goal.png"];
export const ASSET_HOME_GOAL_PROGRESS = ASSET_REGISTRY["/Assets/Finance UI/home_goal_progress.png"];
export const ASSET_SHIELD_PROTECTION = ASSET_REGISTRY["/Assets/Icons And Misc/shield_protection.png"];
export const ASSET_PURPLE_WATERCOLOR_BANNER = ASSET_REGISTRY["/Assets/UI/purple_watercolor_banner.png"];
